cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 26
    - RUBY_VERSION: 25
init:
  - git config --global core.autocrlf true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  # - ps: Install-Product node Current
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake