name: windows
on:
  push:
    branches:
      # - master
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    strategy:
      matrix:
        ruby: ['2.5.x', '2.6.x']
    runs-on: windows-2019
    name: Ruby ${{ matrix.ruby }} on Windows
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Install latest bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run test
        run: bundle exec rake test
      - name: Run spec
        run: bundle exec rake spec
